sonar.projectKey=Boardgame
sonar.projectName=Boardgame
sonar.projectVersion=1.0


# Source directories
sonar.sources=src/main
sonar.tests=src/test

# Compiled classes
sonar.java.binaries=.

# Encoding
sonar.sourceEncoding=UTF-8

# JaCoCo coverage report
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions (avoid scanning generated code and build output)
sonar.exclusions=**/target/**,**/generated/**,**/node_modules/**

# Optional coverage exclusions
sonar.coverage.exclusions=**/config/**,**/dto/**

# SCM
sonar.scm.provider=git